import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./layouts/navbar";
import ActiveRoute from "./components/activeRoute";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dataRoute = () => {};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ActiveRoute />
        {children}
        <NavBar />
      </body>
    </html>
  );
}
